### ISSUE TITLE
MacOS version

### ISSUE THREAD

**Issue by FormalSnake** [face-hh/griddycode#1]
Sorry to be that guy, but a macOS version would be cool

**Comment by face-hh** [comment]
Probably, but I don't own a Mac to test it, so putting one in the Release is out of the question.

You can download [Godot](<https://godotengine.org/>), this source code, and compile it to MacOS

**Comment by dropalways** [comment]
https://youtu.be/gbN1eXFskYU?si=h6hx3malAGrteJJz&t=713

**Comment by insomnia-creator** [comment]
@face-hh i just feel sorry for you

you see we macos users have the balls to buy a 1500 dollar laptop but cannot for the life of us figure out how to compile a project(it's rocket science i know)

never include a macos build, let them learn.

**Comment by insomnia-creator** [comment]
There you go ✌️


![CleanShot 2024-03-19 at 23 17 05](https://github.com/face-hh/griddycode/assets/69950985/7dd95da0-284b-44c2-81a2-e56b3ef06951)

**Comment by FormalSnake** [comment]
Yes, I managed to compile it myself too.

A thing about the file tree is that it starts from the disk root, and not the root of the user which should be fixed.

**Comment by face-hh** [comment]
> Yes, I managed to compile it myself too.
> 
> A thing about the file tree is that it starts from the disk root, and not the root of the user which should be fixed.

https://github.com/face-hh/griddycode/blob/25567b03968371f578a4c9f952de094d3b362d3f/Scripts/file_manager.gd#L11 in here, you can add a case for `macOS` and set the default dir to whatever macOS uses

**Comment by FormalSnake** [comment]
I'll try that when I have time, thanks!

**Comment by funkycharlie** [comment]
I have made a binary for macOS, so if anyone doesn't know how to compile just let me know :)

**Comment by face-hh** [comment]
Closing as there is enough information in this issue for others to compile GriddyCode themselves.
