### ISSUE TITLE
Requires Vulkan even when it can be easily fixed

### ISSUE THREAD

**Issue by Shahzaib1432** [face-hh/griddycode#10]
i dont have vulkan so can you please fix this? Forward+ and Mobile requres Vulkan! Use the Compability Mode, It likely wont change anything + Likely to be faster since this is not a 3D Game

# How To Fix
change the mode from Forward+ to Compability

**Comment by face-hh** [comment]
Unfortunately the Glow feature won't work while using the GL compatability layer as Godot doesn't support it yet. If you wish to use the project on a machine without Vulkan, you could try compiling GriddyCode yourself

**Comment by Shahzaib1432** [comment]
Hm ok
