### ISSUE TITLE
[Windows] Opening Files / Folders outside of the C: Drive

### ISSUE THREAD

**Issue by Kyn21kx** [face-hh/griddycode#103]
# Description
It would be good to be able to open and reference files outside the main drive for those of us who have their code under a separate label (D: drive for example)

**Comment by Symmettry** [comment]
Should be an in-app switcher, but in the meantime:

%appdata%\godot\app_userdata\Bussin GriddyCode\data.save

just change the selected drive

**Comment by ItsTato** [comment]
This issue is a clone of #20.

**Comment by face-hh** [comment]
Duplicate of #20
