### ISSUE TITLE
Please make it a plugin for vscode or jetbrain.

### ISSUE THREAD

**Issue by goddade** [face-hh/griddycode#112]
**Describe the solution you'd like**

Please make it a plugin for vscode or jetbrain.

**Comment by Symmettry** [comment]
No that's stupid, they're our competitors.

**Comment by face-hh** [comment]
> No that's stupid, they're our competitors.

Counter argument: Bussin GriddyCode would benefit from smoothening the line between the customers' current code editor and GriddyCode, which this suggestion implies to do.

**Comment by face-hh** [comment]
wait wrong issue

IT WONT HAPPEN, VSCODE DOESNT ALLOW MODIFYING THE INNER HTML. JETBRAINS IS literally c++ i think lol

**Comment by Symmettry** [comment]
what the deuce face? 😠

**Comment by face-hh** [comment]
erm what the sigma

**Comment by Symmettry** [comment]
ur so skibidi!1!14!
