### ISSUE TITLE
Add shortcuts for UNDO and REDO

### ISSUE THREAD

**Issue by abirabedinkhan** [face-hh/griddycode#117]
**Is your feature request related to a problem? Please describe.**
Yes, this feature request is related to a problem with the current user experience of the code editor. Currently, there are no keyboard shortcuts available for the undo and redo operations, which are essential for efficient code editing. Having to reach for the mouse or trackpad to access these functions interrupts the coding flow and reduces productivity.

**Describe the solution you'd like**
The proposed solution is to introduce keyboard shortcuts for the undo and redo operations in the code editor. Specifically, I would like to request the following shortcuts to be implemented:

- Undo: Ctrl+Z (Windows/Linux) or Cmd+Z (macOS)
- Redo: Ctrl+Shift+Z (Windows/Linux) or Cmd+Shift+Z (macOS)

These are the standard and widely adopted shortcut combinations for undo and redo in most text editors and IDEs, so they would be familiar to most developers. Implementing these shortcuts would streamline the editing process, allowing developers to quickly correct mistakes or revert changes without breaking their typing flow or reaching for the mouse/trackpad.

Additionally, it would be beneficial to provide visual feedback (e.g., a brief tooltip or status bar message) when these shortcuts are used, confirming the undo or redo operation for the user.

**Comment by face-hh** [comment]
I'm pretty sure undo and redo functionality already exists since it's inherited from the CodeEdit node

**Comment by abirabedinkhan** [comment]
Sorry for the misunderstanding It wasn't working but when re-opened it started working again.
