### ISSUE TITLE
3D camera

### ISSUE THREAD

**Issue by MitchTalmadge** [face-hh/griddycode#12]
my coding power is limited with only 2 dimensions. I want to code in 3D. also please add an inventory and zombies. very epic thanks 💯

**Comment by chxdr** [comment]
i actually have somrthing to add to this, if the screen becomes 3d, add depth of field with bokeh and a screen door effect

**Comment by face-hh** [comment]
Unlike other game engines like Unity, a 2D project in Godot remains 2D (unless projected in 3D, which is out of scope for this project)
