### ISSUE TITLE
Volume Slider doesn't mute at 0%

### ISSUE THREAD

**Issue by Sillyram** [face-hh/griddycode#122]
**The Issue**
When the volume slider is set to its minimum value of 0%, music can still be heard faintly.

**To Reproduce**
_Incredibly complicated steps to reproduce are:_
1. Move your mouse cursor over the volume slider
2. **[IMPORTANT!!]** left click and **HOLD** the slider
3. While HOLDING the slider, drag it to the very left.
4. Release the left mouse button.
5. If these instructions are unclear and you end up somewhere unfamiliar, pray to your respective deity or god

**Expected behavior**
The expected behaviour of the volume slider at a value of zero is to mute whatever volume it is controlling.

**Screenshots**
![not0](https://github.com/face-hh/griddycode/assets/140316911/063ad9ef-9ffc-4b47-9079-c6b5e1991d76)

**Desktop:**
 - OS: Windows 11
 - Version v1.2.1

**Comment by SweetyAngel** [comment]
The issue was solved. You can close this issue
