### ISSUE TITLE
I can't open the option

### ISSUE THREAD

**Issue by 0xSYXCYX** [face-hh/griddycode#124]
version:1.2.1
I can't open the option GUI(press CTRL + ,)
Why?

**Comment by face-hh** [comment]
#105 is related. What keyboard layout are you using?

**Comment by 0xSYXCYX** [comment]
System:  WIn11 24H2
Keyboard layout:  ENG(US)

**Comment by face-hh** [comment]
Windows 11 is the problem then. It should work fine on Windows 10 and Linux

**Comment by 0xSYXCYX** [comment]
ok
I see.
