### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Lum000Z** [face-hh/griddycode#141]
I started GriddyCode, colours change (the entire griddycode) and then it just goes black fully. No errors, no nothing. 

OS: Windows 10 (latest x64)

**Comment by SweetyAngel** [comment]
What GriddyCode version do you use?

**Comment by Lum000Z** [comment]
> What GriddyCode version do you use?

v1.2.2

**Comment by ArmanHayots** [comment]
Me too, W11.
Event viewer shows fault in the `C:\WINDOWS\System32\DriverStore\FileRepository\u0402263.inf_amd64_1366da2d694c570c\B400781\amdxc64.dll`, something wrong with graphics initialization.

**Comment by Lum000Z** [comment]
> Me too, W11. Event viewer shows fault in the `C:\WINDOWS\System32\DriverStore\FileRepository\u0402263.inf_amd64_1366da2d694c570c\B400781\amdxc64.dll`, something wrong with graphics initialization.

actually, i use Intel, but it probably has the same issue as AMD.


EDIT: I fixed it somehow... by opening event viewer...
