### ISSUE TITLE
Some unicode characters are broken

### ISSUE THREAD

**Issue by sctech-tr** [face-hh/griddycode#156]
**Describe the bug**
Some unicode characters show as boxes.

**To Reproduce**
Go to the file selection menu.  
See the nonsense.  

**Expected behavior**
I expected the characters to be rendered properly.

**Screenshots**
![resim](https://github.com/user-attachments/assets/133baa2d-9f35-4d5e-a5bf-69399f825f93)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40 (KDE Plasma)
 - Version: v1.2.2

**Comment by zSnails** [comment]
What font are you using? Is that the default font?

**Comment by sctech-tr** [comment]
To the best of my knowledge, I never changed the default font

**Comment by YuvanMichaelVivenzi** [comment]
Bro its Firacode, Find it in settings by using ctrl + ,
install firacode font for your distro and try again.
Hope your issue is resolved!
Kindly close if it is.

**Comment by sctech-tr** [comment]
oh ok thanks!
