### ISSUE TITLE
Holding arrow keys in file selector can cause the highlighted item to disappear

### ISSUE THREAD

**Issue by Symmettry** [face-hh/griddycode#19]
- go file editor in a big folder
- hold down
- highlighted item slowly moves up the screen when going down until it's no longer there.

**Comment by Symmettry** [comment]
actually this happens without holding

**Comment by Symmettry** [comment]
also huge folders lag every time u click up/down

**Comment by face-hh** [comment]
It's a problem with the math calculation, will fix it in the next build

**Comment by face-hh** [comment]
presumably fixed in v1.1.1
