### ISSUE TITLE
Hidden folders don't show up

### ISSUE THREAD

**Issue by Symmettry** [face-hh/griddycode#21]
when opening a folder with hidden files/folders they don't appear (even when ran as admin)
and also in general a bunch of folders just don't show up

**Comment by Symmettry** [comment]
Ah, i see.

If the folder is not capitalized it doesn't show up for some reason

"Bussin" shows up. "bussin" does not

**Comment by face-hh** [comment]
> If the folder is not capitalized it doesn't show up for some reason
Unreplicable

> Hidden folders don't show up
Fixed in v1.1.0

**Comment by Symmettry** [comment]
aight nice. somehow in my user profile folder i was not able to read my lowercase folders idk why

**Comment by face-hh** [comment]
> Hidden folders don't show up. Fixed in v1.1.0
Because the performance issue still exists in the file picker (which causes lag when there are many items to display), I will revert this. It shouldn't be a problem with the introduction of CLI support, as you'll be able to `gcode .test` to change to a hidden directory.
