### ISSUE TITLE
Suggestion: Include line and column in detect_functions and detect_variables

### ISSUE THREAD

**Issue by Symmettry** [face-hh/griddycode#29]
e.g.

function detect_variables(content, line, column)

end

this way scopes can also be detected and so if i have like

function ABC() {
    function DEF() {
    
    }
}

if I'm on the outside of ABC it will tell me ABC() but not DEF(), and if I'm inside it'll tell both

currently it shows both of these even tho DEF() is not always accessible.

**Comment by face-hh** [comment]
Added in v1.1.0 (will release later)
