### ISSUE TITLE
Having file names too long will cut them off the screen

### ISSUE THREAD

**Issue by NOAHBENJ** [face-hh/griddycode#37]
**Describe the bug**
While in the file picker, having file names that are way too long will just cut them off, theres no way to see the full names (the names in the screenshot are just an example, i stumbled into a folder with some logs that had long names that weren't rendered in full length but forgot where they were so just made some up somewhere else)

**To Reproduce**
1. Go to file picker
2. Click on find a file with a really long name
4. See a clipped name (image below)

**Expected behavior**
To see the full name

**Screenshots**
![image](https://github.com/face-hh/griddycode/assets/82064301/a4687dd1-ddde-48ac-9602-5b71d4df696f)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version: Bussin GriddyCode v1.0.4

**Comment by face-hh** [comment]
This will be fixed in v1.1.0, truncating the string instead. 
![image](https://github.com/face-hh/griddycode/assets/69168154/b0ac5433-8542-480b-ae39-63022b55e0d2)

**Comment by face-hh** [comment]
Fixed in v1.1.0
