### ISSUE TITLE
Bug with a large number of lines

### ISSUE THREAD

**Issue by VengryDevs** [face-hh/griddycode#40]
**Describe the bug**
When writing 1700+ lines the screen slides down but the cursor stays in place.

**To Reproduce**
1. Open any file.
2. Write 1700+ lines.
3. See a bug.

**Expected behavior**
I expect the cursor to move with the screen, as it did before 1700+ lines.

**Screenshots**
![image](https://github.com/face-hh/griddycode/assets/86539539/029b1675-5b72-44b4-8068-8ab10aa0bcbf)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Version 1.1.1

**Comment by face-hh** [comment]
Fixed in #57, will be published with the next release
