### ISSUE TITLE
Text is invisible

### ISSUE THREAD

**Issue by Schweeeeeeeeeeeeeeee** [face-hh/griddycode#5]
![image](https://github.com/face-hh/griddycode/assets/88291316/e2740318-612b-45e4-9775-082833ac5eb0)
![image](https://github.com/face-hh/griddycode/assets/88291316/24414fc0-9837-483d-a366-e90c4f7893cb)
[boobs@boobs Linux]$ ./Bussin\ GriddyCode.x86_64 
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.277 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6700 XT
 
SCRIPT ERROR: Cannot call method 'get_files' on a null value.
          at: FileManager.inject_lua (res://Scripts/file_manager.gd:43)
ERROR 6: error while opening file 'user://langs/.lua'
ERROR 6: error while opening file 'user://themes/One Dark Pro Darker.lua'

**Comment by Blackneeed** [comment]
Duplicate of #2

**Comment by jonesy-b-dev** [comment]
Same here on windows

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I get Text when downloading the source code and opening it in godot

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Duplicate of https://github.com/face-hh/griddycode/issues/2

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Duplicate of https://github.com/face-hh/griddycode/issues/2
