### ISSUE TITLE
Unify the syntax of files in the Plugins dir

### ISSUE THREAD

**Issue by uynilo9** [face-hh/griddycode#51]
**Is your feature request related to a problem? Please describe.**
Not really. But they should be unified so they're more readable.

```lua
-- lua.lua
local BINARY = "binary";
local RESERVED = "reserved";
local OPERATOR = "operator";
local VARIABLE = "variable";

local hl = highlight;
local hlreg = highlight_region;

hl("false",BINARY);
hl("true",BINARY);
hl("nil",RESERVED);

-- bs.lua
highlight("let", "reserved")
highlight("const", "reserved")
```

**Describe the solution you'd like**
Including semicolons, alias, quotes, spaces and etc.
For example, we should ban the use of semicolons and alias, and only use " instead of any '

**Comment by face-hh** [comment]
I don't see how this is a problem, the files were created by 2 completely different people with 2 completely different coding styles. Readability wasn't a concern to me while reviewing either at all

**Comment by uynilo9** [comment]
I see. Thanks for your answer <3
