### ISSUE TITLE
c# lang

### ISSUE THREAD

**Issue by toby-gamez** [face-hh/griddycode#53]
Please, add c# lang
thanks 😉

**Comment by uynilo9** [comment]
why don't you yourself implement it and make a PR

**Comment by Blackneeed** [comment]
yeah just make a lua extension

**Comment by Blackneeed** [comment]
not that hard

**Comment by RealPacket** [comment]
> why don't you yourself implement it and make a PR

I'm going to try and make a monarch language converter for griddy code because funny

**Comment by Symmettry** [comment]
You barely even need lua experience to make syntax highlighters for GriddyCode.

Google "c# keywords", "c# variables", and "c# function declaration" and you'll have all the resources you need.

**Comment by ItsTato** [comment]
Imma go ahead and make one then.

I'll submit the PR and link it here once I'm done

**Comment by Symmettry** [comment]
You can say "fixes #53" in the PR description and it'll link here to close it

**Comment by ItsTato** [comment]
Will do then

**Comment by RealPacket** [comment]
> > why don't you yourself implement it and make a PR
> 
> I'm going to try and make a monarch language converter for griddy code because funny (written in Rust)

it currently supports keywords.

**Comment by RealPacket** [comment]
I've added C# language support. PR: #82
