### ISSUE TITLE
LuaAPI class not found - needed to start the project

### ISSUE THREAD

**Issue by vPumpking** [face-hh/griddycode#56]
**Describe the bug**
When attempting to launch the game project on linux, x86_64, 12Gb RAM, the following message appears:
![image](https://github.com/face-hh/griddycode/assets/121762735/b1c6e683-b2a0-471a-a256-9a9a874cb57a)

**To Reproduce**
Download the project by cloning the repository, then try to start it with Godot 4.2 stable

**Expected behavior**
Obviously, this external class should already be included in the project. Do I need to install the LuaAPI extension from the AssetLibrary?

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 2310
 - Version : latest main branch

**Comment by face-hh** [comment]
Open the project settings, and under Plugins enable LuaAPI and DiscordSDK

**Comment by vPumpking** [comment]
Yeah I immediately thought about that, but even though the .gedextension file exists in the `addons` directory, it doesn't appear in the settings

**Comment by vPumpking** [comment]
Ok, I spotted what the error was: I use godot 4.2 and the addon is build for 4.2.1
you maybe should specify this in the readme
