### ISSUE TITLE
More Languages

### ISSUE THREAD

**Issue by MrSmile227** [face-hh/griddycode#59]
Please add more programming languages, for example Java, Python

**Comment by face-hh** [comment]
Java was already added, and python is in the works on a pull request

**Comment by MrSmile227** [comment]
> Java was already added, and python is in the works on a pull request

I tried to use Python but I couldn't. It said that this file is not supported (.py)

**Comment by zSnails** [comment]
@MrSmile227 
> python is in the works on a pull request
