### ISSUE TITLE
windows version camera movement incorrect

### ISSUE THREAD

**Issue by marmust** [face-hh/griddycode#6]
I'm on windows 10
The first time I opened the exe the music worked but not the visuals, so I closed it mid loading to restart but now nothing works :(
what I think is going on is that the position of the camera is somehow off.
when I restart the editor I see the first line number appear for one frame, then everything disappears (I think because the text just flies off)
it might be somehow because I have two monitors so the resolution is not good but when I disconnected one of them, the issue persists.
super cool editor tho :)

**Comment by face-hh** [comment]
Could you try the v1.0.3 version? It should fix some issues, and if it persists, could you share a screenshot or video of it?

**Comment by marmust** [comment]
nvm fixed in version 1.0.3 👍 ty
