### ISSUE TITLE
Use Luau instead of Lua

### ISSUE THREAD

**Issue by RealPacket** [face-hh/griddycode#64]
**Is your feature request related to a problem? Please describe.**
Use [Luau](https://luau-lang.org) instead of [Lua](https://lua.org).
It's essentially typed Lua.
The "we need TypeScript plugin support in GriddyCode" people will shut up because Luau has types, or just use Roblox-TS.
It's compatible with Lua 5.1 code so most code should work.

**Describe the solution you'd like**
Use Luau instead of Lua. You can probably use [godot-luau-script](https://github.com/Fumohouse/godot-luau-script) in this case.

**Comment by face-hh** [comment]
For now we're not gonna switch from LuaAPI as it provides too little benefit. Neovim doesn't use it either, and it seems to work just fine for developers :^)

**Comment by zSnails** [comment]
The plugins api has like 6 functions, and if you're using [luals](https://github.com/LuaLS/lua-language-server) (formerly known as sumneko_lua) the meta file at the project root should provide you with the necessary type definitions you need.

**Comment by RealPacket** [comment]
> For now we're not gonna switch from LuaAPI as it provides too little benefit. Neovim doesn't use Luau either, and it seems to work just fine for developers :^)

Did you read the website?
Luau has `continue`, types, and more (it does remove goto, but honestly,
you shouldn't need it other than for continuing in a for loop).
Why would Roblox create Luau in the first place if there was no reason to?

> The plugins api has like 6 functions, and if you're using [luals](https://github.com/LuaLS/lua-language-server) (formerly known as sumneko_lua) the meta file at the project root should provide you with the necessary type definitions you need.

Yes. However, it's not natively supported by Lua.

**Comment by ItsTato** [comment]
> > For now we're not gonna switch from LuaAPI as it provides too little benefit. Neovim doesn't use Luau either, and it seems to work just fine for developers :^)
> 
> Did you read the website? Luau has `continue`, types, and more (it does remove goto, but honestly, you shouldn't need it other than for continuing in a for loop). Why would Roblox create Luau in the first place if there was no reason to?
> 
> > The plugins api has like 6 functions, and if you're using [luals](https://github.com/LuaLS/lua-language-server) (formerly known as sumneko_lua) the meta file at the project root should provide you with the necessary type definitions you need.
> 
> Yes. However, it's not natively supported by Lua.

I think the benefit of implementing Luau is minimal.

GriddyCode should stick to Lua unless the need for Luau arises.

**Comment by RealPacket** [comment]
Ok. I'll close the issue for now.
