### ISSUE TITLE
Windows 1.0.3: File browser cuts off content when there is a lot of files

### ISSUE THREAD

**Issue by NorteX-dev** [face-hh/griddycode#7]
Using 1.0.3.

When opening a folder with a lot of subdirectories/subfiles, the content cuts off.

Attached video.

https://github.com/face-hh/griddycode/assets/32877032/b496f2ec-e698-4fb3-8dc8-214fc3f852f7

Clicking Enter while on the invisible screen seems to navigate to the folder properly however.

**Comment by dropalways** [comment]
yep same

**Comment by face-hh** [comment]
The limit has been increased in v1.0.4 (will release later). To fix this completely, #8 would have to be implemented.
