### ISSUE TITLE
Font resolution is low on MacOS without building (will test built version later)

### ISSUE THREAD

**Issue by MinecraftPublisher** [face-hh/griddycode#71]
Also, Zed was not built exclusively for MacOS and they're working on a Linux and Windows release.

Plus, I could build the Mac version for you if you want

**Comment by face-hh** [comment]
We won't support the fruit os as I don't want to rely on someone else to test each build

**Comment by face-hh** [comment]
Duplicate of #72

**Comment by MinecraftPublisher** [comment]
wait why was it posted twice damn
