### ISSUE TITLE
Code Editor Window Resizing Issue

### ISSUE THREAD

**Issue by 010101-sans** [face-hh/griddycode#75]
**Describe the bug**
The code editor does not auto-adjust its inner content when the window size is changed. When either the length or height of the window is larger than the other, the code editor gets cramped, failing to show consistent sizes of elements regardless of the aspect ratio of the window.

**To Reproduce**
1. Open the code editor.
2. Change the window size, making either the length or height larger than the other.
3. Observe the inner content of the code editor.

**Expected behavior**
The code editor should auto-adjust its inner content to maintain consistent sizes of elements, regardless of the aspect ratio of the window. The content should not appear cramped when the window size is changed.

**Screenshots**

![image](https://github.com/face-hh/griddycode/assets/71075748/b7a22e40-42fd-47b5-a0f2-a3c9fefb390b)

**Desktop:**
 - OS: Windows 11
 - Version 1.1.1

**Comment by Blackneeed** [comment]
Face knows. If you running from godot in the window settings set aspect to keep height

**Comment by face-hh** [comment]
Fixed in 68d5ec4. Will be shipped in v1.2.0

**Comment by 010101-sans** [comment]
Awesome 👍🏻
