### ISSUE TITLE
Text size modifier keyboard shortcuts

### ISSUE THREAD

**Issue by MinecraftPublisher** [face-hh/griddycode#77]
**Is your feature request related to a problem? Please describe.**
<img width="1920" alt="image" src="https://github.com/face-hh/griddycode/assets/44898501/36b9755a-4453-4081-8130-c520671a0c83">
^^ Too smol :(

**Describe the solution you'd like**
Add `Ctrl +` and `Ctrl -` scale changer keys to increase/decrease font-size on the fly

**Comment by face-hh** [comment]
The zooms are hardcoded so this won't be possible, and neither is it on the roadmap

**Comment by MinecraftPublisher** [comment]
Just tell me where the zooming function is and i'll fix it and make a PR

**Comment by face-hh** [comment]
Camera.gd, and there's a "zoom_to_..." function at the end of a file somewhere

**Comment by MinecraftPublisher** [comment]
i found a function called `to_zoom`. how does it work? what is the max and min of the zoom? does it zoom more the bigger the value is?

**Comment by face-hh** [comment]
I forgor, check where it's used

**Comment by MinecraftPublisher** [comment]
uhhhh.... how?

**Comment by MinecraftPublisher** [comment]
found the actual function. it's `_process` in `camera.gd`. now gonna learn how to receive key combinations in gdscript. brb

**Comment by MinecraftPublisher** [comment]
also btw where do i set the font for the program in the code

**Comment by MinecraftPublisher** [comment]
because all the fonts are set to fira code in the editor itself and thats the only font in the Fonts directory alongside Noto Color Emoji and the problem is that i have the JetBrainsMono Nerd Font installed

**Comment by MinecraftPublisher** [comment]
done! zoom functions working. opening PR in a moment
