### ISSUE TITLE
File is trimmed at 272 lines

### ISSUE THREAD

**Issue by MinecraftPublisher** [face-hh/griddycode#79]
**Describe the bug**
<img width="1920" alt="image" src="https://github.com/face-hh/griddycode/assets/44898501/fc88e88d-d6df-47c7-81f0-fb1073961d72">
^^^ the file in question is 1640 lines

**To Reproduce**
1. Open big file
2. Go to end of big file
3. Big file no big big file smol :(

**Expected behavior**
The file should not be trimmed, Unlike the file picker which i mentioned in the previous issue

**Comment by Symmettry** [comment]
![image](https://github.com/face-hh/griddycode/assets/109181931/5a9434d3-c1d3-40eb-8b11-9347a6ea70c6)
I can't reproduce this. What version are you on?

**Comment by MinecraftPublisher** [comment]
v1.1.1

**Comment by MinecraftPublisher** [comment]
it somehow works now. i'll check what's causing this
