### ISSUE TITLE
Syntax highlights is automated in certain files that is unwanted

### ISSUE THREAD

**Issue by Symmettry** [face-hh/griddycode#81]
**Describe the bug**
Stuff like numbers, commas, symbols, etc. is highlighted everywhere which has some problems

**To Reproduce**
1. make a txt file
2. type stuff like "and" or "of"
3. it highlights.

**Expected behavior**
.txt files should not have any highlighting.

**Screenshots**
![image](https://github.com/face-hh/griddycode/assets/109181931/5ab3b279-8fb5-456e-89b4-a6e2653bd2aa)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. v1.0.3] v1.1.1

**Comment by ItsTato** [comment]
Try closing and re-launching the editor. It may be caching the highlight instructions from another language (if you've opened any file that is compatible or has a .lua file for it, the editor is infamous for not clearing that)

If after re-launching the editor and opening only that .txt file it still happens then 😭

**Comment by Symmettry** [comment]
The old symbols clear, but there are still highlights that shouldn't exist (e.g. binary operators, commas, and periods)

**Comment by ItsTato** [comment]
Those are provided by our face-hh overlord

**Comment by face-hh** [comment]
This is because the CodeEdit node has the option to highlight the symbols, functions, etc., something the themes API takes advantage of. It can be disabled, and we could add something like `disable_highlighting()` to the plugins API for stuff like txt, but I really don't see a need in that as txt doesn't require any plugin at all

**Comment by face-hh** [comment]
Merging issue with #92

**Comment by RealPacket** [comment]
> Merging issue with #92

I think #92 is unrelated to this issue, this issue is related to language data not being cleared, and #92 is related to languages not having enough control over the CodeEdit node.
