### ISSUE TITLE
Mac builds in releases?

### ISSUE THREAD

**Issue by Moosems** [face-hh/griddycode#83]
**Is your feature request related to a problem? Please describe.**
I would like a .app executable to get from the downloads page, would be very nice

**Describe the solution you'd like**
An automated Mac executable that goes in releases

**Comment by Moosems** [comment]
<img width="212" alt="Screenshot 2024-03-25 at 8 09 03 PM" src="https://github.com/face-hh/griddycode/assets/95927277/66930697-ca82-4211-9121-248fd7143c53">

**Comment by RealPacket** [comment]
I'm thinking about automating it with GitHub Actions.

**Comment by Moosems** [comment]
Are the others not?

**Comment by RealPacket** [comment]
Maybe this will work: <https://github.com/aBARICHELLO/godot-ci/>

**Comment by RealPacket** [comment]
<https://github.com/RealPacket/griddycode/actions/runs/8429747951> I tried, despite the actions all "passing", they threw 500 errors, and the actions never uploaded the build artifact... Not sure why it doesn't work, I didn't modify any of the src code in that branch...

**Comment by RealPacket** [comment]
> Did y'all not watch the video? There won't be apple support

I did. I'm not a Mac user but I think all platforms should be supported if possible, after all, the more supported platforms, the more accessible it is. Obviously it isn't going to run on DOS but...

**Comment by zSnails** [comment]
That for @face-hh to decide

**Comment by agusibrahim** [comment]
plz add mac app in releases

**Comment by RealPacket** [comment]
I have no idea how to build it right now, but it's not working for me or the actions...

**Comment by face-hh** [comment]
Refer to #1 to check how to compile the project yourself for macOS. As I've previously mentioned, I won't add a macOS build to the releases because I have no way of testing
