### ISSUE TITLE
Cant figure out Nerdfont

### ISSUE THREAD

**Issue by LOLYAYDEV** [face-hh/griddycode#9]
I tried installing every font on the nerdfont website but i still se the glyphs. What fonts should i doenload and where. Im using windows 11

**Comment by rottakore** [comment]
I think you only need one nerdfont, the problem is that there's no way to configure the font in the app, I think it defaults to the primary font of the OS

**Comment by 7valkio** [comment]
I have installed the FiraCode Nerd Font and FiraMono Nerd Font but when I open the Griddycode, it still gives blurry characters.

https://github.com/face-hh/griddycode/assets/113270877/2a906792-698f-4d7b-b805-aaaf8b929f82

**Comment by BurningButter** [comment]
Try 0xProto Nerd Font, its the first one that pops up and it worked for me.

**Comment by 7valkio** [comment]
I tried installing the 0xProto Nerd Font, still showing blurry on Windows 11.

**Comment by ThreeTheOG** [comment]
Same here.

**Comment by face-hh** [comment]
Closing as it now works on v1.0.4
