### ISSUE TITLE
Syntax highlighting in Go

### ISSUE THREAD

**Issue by uynilo9** [face-hh/griddycode#99]
**Describe the bug**
See the image below

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
![image](https://github.com/face-hh/griddycode/assets/115794240/d72e969f-38cf-4eb1-8dc8-c1c74e2f1bf1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v1.2.0

**Comment by ItsTato** [comment]
#101 explains this issue

**Comment by ItsTato** [comment]
Heyo, you said you were using Win10?
Did you build yourself or download the executable?

**Comment by uynilo9** [comment]
> Heyo, you said you were using Win10?
> Did you build yourself or download the executable?

I did download the executable instead of building
Is this the actual cause
